### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by vtjnash** [thenumbernine/black-hole-skymap#1]
This looks like a really cool project. I'd like to remix and play with it more, and learn about the math and physics behind it. Unfortunately, I didn't see a LICENSE file. Would you mind adding one? I'm partial to the MIT/BSD/ISC family of licenses, but maybe you already had an idea about what you wanted to allow people to do with the code.

**Comment by thenumbernine** [comment]
Sure thing, done
